### ISSUE TITLE
Failure in ModelEvaluator serialization

### ISSUE THREAD

**Issue by mpeychev** [jpmml/jpmml-evaluator#103]
Hello,

I am trying to serialize a `ModelEvaluator` object and write it in a file. However, although this class implements `Serializable`, I am receiving a `NotSerializableException` exception. Full steps to reproduce follow below:

Code
```
PMML pmml;
String path = "/path/to/random_forest_pmml_pipeline.pmml";
try(InputStream is = new FileInputStream(new File(path))) {
	pmml = PMMLUtil.unmarshal(is);
}

ModelEvaluatorFactory modelEvaluatorFactory = ModelEvaluatorFactory.newInstance();
ModelEvaluator<?> modelEvaluator = modelEvaluatorFactory.newModelEvaluator(pmml);
Evaluator evaluator = (Evaluator) modelEvaluator;

FileOutputStream f_out = new FileOutputStream("/path/to/model.data");
ObjectOutputStream obj_out = new ObjectOutputStream(f_out);
obj_out.writeObject(modelEvaluator);
```

Error stack trace:
```
java.io.NotSerializableException: org.xml.sax.helpers.LocatorImpl

	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at java.util.LinkedHashMap.internalWriteEntries(LinkedHashMap.java:333)
	at java.util.HashMap.writeObject(HashMap.java:1362)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
```

Also, I am assuming deserializing the object would be generally faster than unmarshalling. Is this correct?

Thank you,
Momchil

**Comment by vruusmann** [comment]
It's the `org.dmg.pmml.PMML` class model object that contains non-serializable SAX Locator information. It can be removed, or transformed to serializable form.

See https://github.com/jpmml/jpmml-model/issues/10#issuecomment-259846557

> Also, I am assuming deserializing the object would be generally faster than unmarshalling. Is this correct?

You should run your own experiments. Java's JAXB unmarshaller stack is quite good (hundreds of MB/sec on a desktop PC). Not sure at all that `java.io.ObjectInputStream#readObject()` can keep up with that (especially if the PMML class model object contains many cross-references, eg. after it has been optimized and interned).
