### ISSUE TITLE
[Question:] multinomial logistic regression PMML

### ISSUE THREAD

**Issue by mmerce** [jpmml/jpmml-evaluator#113]
The jpmml-evaluator fails to run the test example for the PMML below, that tries to represent a one-vs-rest multinomial logistic regression. Is that something that can be done using the jpmml-evaluator? Maybe there's some kind of mistake in the PMML code, but I cannot find it. I believe I've found a working example in the test cases but it uses one of the classes as target reference. Does that mean that  we unavoidably need to produce a separate PMML per category?

Also, I'd like to know if there's any validation tool or a complete set of examples that can tell us what type of PMML schemas are compatible with jpmml-evaluator. It would help a lot if you could point me to it.

Thank you.

```xml
<?xml version="1.0" ?>
<PMML version="4.2" xmlns="http://www.dmg.org/PMML-4_2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Header description="Generated by BigML"/>
	<DataDictionary>
		<DataField dataType="double" displayName="Sepal_Length" name="Sepal_Length" optype="continuous"/>
		<DataField dataType="double" displayName="Sepal_Width" name="Sepal_Width" optype="continuous"/>
		<DataField dataType="double" displayName="Petal_Length" name="Petal_Length" optype="continuous"/>
		<DataField dataType="double" displayName="Petal_Width" name="Petal_Width" optype="continuous"/>
		<DataField dataType="string" displayName="Species" name="Species" optype="categorical">
			<Value value="setosa"/>
			<Value value="versicolor"/>
			<Value value="virginica"/>
		</DataField>
	</DataDictionary>
	<GeneralRegressionModel functionName="classification" modelName="5af3416919536414159b7664" modelType="multinomialLogistic">
		<MiningSchema>
			<MiningField name="Sepal_Length"/>
			<MiningField name="Sepal_Width"/>
			<MiningField name="Petal_Length"/>
			<MiningField name="Petal_Width"/>
			<MiningField name="Species" usageType="target"/>
		</MiningSchema>
		<Output>
			<OutputField name="Species" optype="categorical" dataType="string" feature="predictedDisplayValue"/>
		</Output>
		<ParameterList>
			<Parameter label="Sepal_Length" name="p0"/>
			<Parameter label="Sepal_Width" name="p1"/>
			<Parameter label="Petal_Length" name="p2"/>
			<Parameter label="Petal_Width" name="p3"/>
			<Parameter label="bias" name="p4"/>
		</ParameterList>
		<FactorList/>
		<CovariateList>
			<Predictor name="Sepal_Length"/>
			<Predictor name="Sepal_Width"/>
			<Predictor name="Petal_Length"/>
			<Predictor name="Petal_Width"/>
		</CovariateList>
		<PPMatrix>
			<PPCell parameterName="p0" predictorName="Sepal_Length" value="1"/>
			<PPCell parameterName="p1" predictorName="Sepal_Width" value="1"/>
			<PPCell parameterName="p2" predictorName="Petal_Length" value="1"/>
			<PPCell parameterName="p3" predictorName="Petal_Width" value="1"/>
		</PPMatrix>
		<ParamMatrix>
			<PCell beta="-0.81323" parameterName="p0" targetCategory="setosa" df="1"/>
			<PCell beta="1.40146" parameterName="p1" targetCategory="setosa" df="1"/>
			<PCell beta="-1.6887" parameterName="p2" targetCategory="setosa" df="1"/>
			<PCell beta="-1.5149" parameterName="p3" targetCategory="setosa" df="1"/>
			<PCell beta="-1.61372" parameterName="p4" targetCategory="setosa" df="1"/>
			<PCell beta="0.13742" parameterName="p0" targetCategory="versicolor" df="1"/>
			<PCell beta="-1.26243" parameterName="p1" targetCategory="versicolor" df="1"/>
			<PCell beta="0.79078" parameterName="p2" targetCategory="versicolor" df="1"/>
			<PCell beta="-0.91468" parameterName="p3" targetCategory="versicolor" df="1"/>
			<PCell beta="-0.89788" parameterName="p4" targetCategory="versicolor" df="1"/>
			<PCell beta="0.01398" parameterName="p0" targetCategory="virginica" df="1"/>
			<PCell beta="-0.14233" parameterName="p1" targetCategory="virginica" df="1"/>
			<PCell beta="1.86559" parameterName="p2" targetCategory="virginica" df="1"/>
			<PCell beta="2.70279" parameterName="p3" targetCategory="virginica" df="1"/>
			<PCell beta="-2.70346" parameterName="p4" targetCategory="virginica" df="1"/>
		</ParamMatrix>
	</GeneralRegressionModel>
</PMML>
```

**Comment by vruusmann** [comment]
> The jpmml-evaluator fails to run the test example for the PMML below

What is the exception message?

**Comment by mmerce** [comment]
Thanks for your quick answer. The message is:

> Conflict{id=149, arguments={Sepal_Length=5.9, Sepal_Width=3, Petal_Length=5.1, Petal_Width=1.8, Species=virginica}, exception=org.jpmml.evaluator.InvalidElementException: Element ParamMatrix is not valid}

**Comment by vruusmann** [comment]
This is the exception that I see:
```
Exception in thread "main" org.jpmml.evaluator.InvalidElementException (at or around line 46 of the PMML document): Element ParamMatrix is not valid
        at org.jpmml.evaluator.general_regression.GeneralRegressionModelEvaluator.parseTargetCategories(GeneralRegressionModelEvaluator.java:822)
        at org.jpmml.evaluator.general_regression.GeneralRegressionModelEvaluator.getTargetCategories(GeneralRegressionModelEvaluator.java:774)
        at org.jpmml.evaluator.general_regression.GeneralRegressionModelEvaluator.evaluateClassification(GeneralRegressionModelEvaluator.java:347)
        at org.jpmml.evaluator.general_regression.GeneralRegressionModelEvaluator.evaluate(GeneralRegressionModelEvaluator.java:176)
        at org.jpmml.evaluator.ModelEvaluator.evaluate(ModelEvaluator.java:434)
        at org.jpmml.evaluator.EvaluationExample.execute(EvaluationExample.java:298)
        at org.jpmml.evaluator.Example.execute(Example.java:86)
        at org.jpmml.evaluator.EvaluationExample.main(EvaluationExample.java:180)
```

This is the relevant code block:
https://github.com/jpmml/jpmml-evaluator/blob/master/pmml-evaluator/src/main/java/org/jpmml/evaluator/general_regression/GeneralRegressionModelEvaluator.java#L817-L823

BigML is specifying three reference categories, but it should be specifying only one?

**Comment by vruusmann** [comment]
> BigML is specifying three reference categories, but it should be specifying only one?

Or two instead of three. Please see the PMML specification for valid examples, and ultimate truth.

**Comment by mmerce** [comment]
Oh, I think I found the relevant part of it for this case, and you are right. 

> targetReferenceCategory: can be used for specifying the reference category of the target variable in a multinomial classification model. Normally the reference category is the one from DataDictionary that does not appear in the ParamMatrix, but when several models are combined in one PMML file an explicit specification is needed.

I'll try that, sorry for bothering you. Best.

**Comment by vruusmann** [comment]
Maybe you should set the `GeneralRegressionModel@targetReferenceCategory` attribute explicitly?

**Comment by mmerce** [comment]
Yes, I'm afraid that's what we'll need to do for each category, so that means three different models instead of one...

**Comment by cheesinglee** [comment]
Hi, I've been working with @mmerce to make BigML's logistic regression models consumable by jpmml-evaluator. Currently, binary classifiers appear to be working as `RegressionModel`s with `normalization="
softmax"`, but I think I may have encountered an issue while trying to get the multi-class models working. 

One thing that perhaps hasn't been made clear in the preceding conversation is that BigML multi-class logistic regression models are not true multinomial or softmax regression models. Rather we train multiple one-vs-rest models and normalize the computed probabilities via simplemax. There doesn't appear to be anything in the PMML spec that describes this application, so my approach is to create a `MiningModel` ensemble where each `Segment` contains one of the one-vs-rest models. Each submodel would output the raw log-odds, and I would do the logit transformation and normalization as `OutputField`s in the top-level model. Here is an example using iris ([gist](https://gist.github.com/cheesinglee/53f77cecf86666a1f103f55c8c1e53ef)), without the output fields yet:

```xml
<?xml version="1.0" encoding="UTF-8"?><PMML xmlns="http://www.dmg.org/PMML-4_3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="4.3">
  <Header description="Model kind: logistic">
    <Application name="BigML"/>
  </Header>
  <DataDictionary>
    <DataField name="sepal length" displayName="" optype="continuous" dataType="double">
      <Extension name="BigML-Field_ID" value="000000"/>
    </DataField>
    <DataField name="sepal width" displayName="" optype="continuous" dataType="double">
      <Extension name="BigML-Field_ID" value="000001"/>
    </DataField>
    <DataField name="petal length" displayName="" optype="continuous" dataType="double">
      <Extension name="BigML-Field_ID" value="000002"/>
    </DataField>
    <DataField name="petal width" displayName="" optype="continuous" dataType="double">
      <Extension name="BigML-Field_ID" value="000003"/>
    </DataField>
    <DataField name="species" displayName="" optype="categorical" dataType="string">
      <Extension name="BigML-Field_ID" value="000004"/>
      <Value value="Iris-setosa"/>
      <Value value="Iris-versicolor"/>
      <Value value="Iris-virginica"/>
    </DataField>
  </DataDictionary>
  <MiningModel modelName="" functionName="classification">
    <MiningSchema>
      <MiningField name="sepal length"/>
      <MiningField name="sepal width"/>
      <MiningField name="petal length"/>
      <MiningField name="petal width"/>
      <MiningField name="species" usageType="target"/>
    </MiningSchema>
    <Output>
      <OutputField optype="continuous" dataType="double" targetField="species" feature="probability" name="log-odds-Iris-setosa" value="Iris-setosa"/>
      <OutputField optype="continuous" dataType="double" targetField="species" feature="probability" name="log-odds-Iris-versicolor" value="Iris-versicolor"/>
      <OutputField optype="continuous" dataType="double" targetField="species" feature="probability" name="log-odds-Iris-virginica" value="Iris-virginica"/>
    </Output>
    <MiningSchema>
      <MiningField name="sepal length"/>
      <MiningField name="sepal width"/>
      <MiningField name="petal length"/>
      <MiningField name="petal width"/>
      <MiningField name="species" usageType="target"/>
    </MiningSchema>
    <LocalTransformations>
      <DerivedField name="sepal length-missing" optype="categorical" dataType="string">
        <MapValues mapMissingTo="true" defaultValue="false" outputColumn="none">
          <FieldColumnPair field="sepal length" column="none"/>
        </MapValues>
      </DerivedField>
      <DerivedField name="sepal width-missing" optype="categorical" dataType="string">
        <MapValues mapMissingTo="true" defaultValue="false" outputColumn="none">
          <FieldColumnPair field="sepal width" column="none"/>
        </MapValues>
      </DerivedField>
      <DerivedField name="petal length-missing" optype="categorical" dataType="string">
        <MapValues mapMissingTo="true" defaultValue="false" outputColumn="none">
          <FieldColumnPair field="petal length" column="none"/>
        </MapValues>
      </DerivedField>
      <DerivedField name="petal width-missing" optype="categorical" dataType="string">
        <MapValues mapMissingTo="true" defaultValue="false" outputColumn="none">
          <FieldColumnPair field="petal width" column="none"/>
        </MapValues>
      </DerivedField>
      <DerivedField name="species-Iris-setosa" optype="categorical" dataType="string">
        <MapValues mapMissingTo="true" defaultValue="false" outputColumn="binarized">
            <FieldColumnPair field="species" column="species"/>
            <InlineTable>
                <row><species>"Iris-setosa"</species><binarized>"Iris-setosa"</binarized></row>
                <row><species>"Iris-versicolor"</species><binarized>"not-Iris-setosa"</binarized></row>
                <row><species>"Iris-virginica"</species><binarized>"not-Iris-setosa"</binarized></row>
            </InlineTable>
        </MapValues>
      </DerivedField>
      <DerivedField name="species-Iris-versicolor" optype="categorical" dataType="string">
        <MapValues mapMissingTo="true" defaultValue="false" outputColumn="binarized">
            <FieldColumnPair field="species" column="species"/>
            <InlineTable>
                <row><species>"Iris-setosa"</species><binarized>"not-Iris-versicolor"</binarized></row>
                <row><species>"Iris-versicolor"</species><binarized>"Iris-versicolor"</binarized></row>
                <row><species>"Iris-virginica"</species><binarized>"not-Iris-versicolor"</binarized></row>
            </InlineTable>
        </MapValues>
      </DerivedField>
      <DerivedField name="species-Iris-virginica" optype="categorical" dataType="string">
        <MapValues mapMissingTo="true" defaultValue="false" outputColumn="binarized">
            <FieldColumnPair field="species" column="species"/>
            <InlineTable>
                <row><species>"Iris-setosa"</species><binarized>"not-Iris-virginica"</binarized></row>
                <row><species>"Iris-versicolor"</species><binarized>"not-Iris-virginica"</binarized></row>
                <row><species>"Iris-virginica"</species><binarized>"Iris-virginica"</binarized></row>
            </InlineTable>
        </MapValues>
      </DerivedField>
    </LocalTransformations>
    <Segmentation multipleModelMethod="selectAll">
      <Segment id="Iris-setosa">
        <True/>
        <RegressionModel functionName="classification" modelType="logisticRegression" normalizationMethod="softmax" modelName=" Iris-setosa">
          <MiningSchema>
            <MiningField name="sepal length"/>
            <MiningField name="sepal width"/>
            <MiningField name="petal length"/>
            <MiningField name="petal width"/>
            <MiningField name="species-Iris-setosa" usageType="target"/>
          </MiningSchema>
          <RegressionTable targetCategory="Iris-setosa" intercept="0">
            <NumericPredictor name="sepal length" coefficient="0.446112"/>
            <NumericPredictor name="sepal width" coefficient="1.48875"/>
            <NumericPredictor name="petal length" coefficient="-2.26038"/>
            <NumericPredictor name="petal width" coefficient="-1.02462"/>
            <CategoricalPredictor name="sepal length-missing" value="true" coefficient="0"/>
            <CategoricalPredictor name="sepal width-missing" value="true" coefficient="0"/>
            <CategoricalPredictor name="petal length-missing" value="true" coefficient="0"/>
            <CategoricalPredictor name="petal width-missing" value="true" coefficient="0"/>
          </RegressionTable>
          <RegressionTable targetCategory="not-Iris-setosa" intercept="0"/>
        </RegressionModel>
      </Segment>
      <Segment id="Iris-versicolor">
        <True/>
        <RegressionModel functionName="classification" modelType="logisticRegression" normalizationMethod="softmax" modelName=" Iris-versicolor">
          <MiningSchema>
            <MiningField name="sepal length"/>
            <MiningField name="sepal width"/>
            <MiningField name="petal length"/>
            <MiningField name="petal width"/>
            <MiningField name="species-Iris-versicolor" usageType="target"/>
          </MiningSchema>
          <RegressionTable targetCategory="Iris-versicolor" intercept="0">
            <NumericPredictor name="sepal length" coefficient="0.580767"/>
            <NumericPredictor name="sepal width" coefficient="-1.49776"/>
            <NumericPredictor name="petal length" coefficient="0.547438"/>
            <NumericPredictor name="petal width" coefficient="-1.44438"/>
            <CategoricalPredictor name="sepal length-missing" value="true" coefficient="0"/>
            <CategoricalPredictor name="sepal width-missing" value="true" coefficient="0"/>
            <CategoricalPredictor name="petal length-missing" value="true" coefficient="0"/>
            <CategoricalPredictor name="petal width-missing" value="true" coefficient="0"/>
          </RegressionTable>
          <RegressionTable targetCategory="not-Iris-versicolor" intercept="0"/>
        </RegressionModel>
      </Segment>
      <Segment id="Iris-virginica">
        <True/>
        <RegressionModel functionName="classification" modelType="logisticRegression" normalizationMethod="softmax" modelName=" Iris-virginica">
          <MiningSchema>
            <MiningField name="sepal length"/>
            <MiningField name="sepal width"/>
            <MiningField name="petal length"/>
            <MiningField name="petal width"/>
            <MiningField name="species-Iris-virginica" usageType="target"/>
          </MiningSchema>
          <RegressionTable targetCategory="Iris-virginica" intercept="0">
            <NumericPredictor name="sepal length" coefficient="-1.8639"/>
            <NumericPredictor name="sepal width" coefficient="-1.64704"/>
            <NumericPredictor name="petal length" coefficient="2.47839"/>
            <NumericPredictor name="petal width" coefficient="2.59359"/>
            <CategoricalPredictor name="sepal length-missing" value="true" coefficient="0"/>
            <CategoricalPredictor name="sepal width-missing" value="true" coefficient="0"/>
            <CategoricalPredictor name="petal length-missing" value="true" coefficient="0"/>
            <CategoricalPredictor name="petal width-missing" value="true" coefficient="0"/>
          </RegressionTable>
          <RegressionTable targetCategory="not-Iris-virginica" intercept="0"/>
        </RegressionModel>
      </Segment>
    </Segmentation>
  </MiningModel>
</PMML>
```
In the top-level LocalTransformations, I am creating a binarized version of the target field for each submodel, and using those `DerivedField`s in the `MiningSchema`s of the submodels. If I am interpreting the [PMML Field Scope documentation](http://dmg.org/pmml/v4-3/FieldScope.html), this is allowed by the spec. I am able to instantiate an `Evaluator` from this document using `ModelEvaluatorFactor.newInstance()`, but when I try to give it input, I see this exception:

```MissingFieldException Field "species-Iris-setosa" is not defined  org.jpmml.evaluator.ModelEvaluator.createTargetFields (ModelEvaluator.java:563)```

From a superficial inspection of `ModelEvaluator.java`, it looks like target fields are only being searched in the `DataDictionary`, and not any other places where they may be defined in a parent model. I'd like to confirm if this is the case, and if so, whether this is a bug in the consumer, or an error on my part.

**Comment by vruusmann** [comment]
> It looks like target fields are only being searched in the DataDictionary

Yes, it is my understanding/interpretation of the PMML specification, that the "definition" of the target field must be represented using the `DataField` element. You could use a thinking pattern that input fields may be "direct" (`DataField` element) or "transformed" (`DerivedField` element), but result fields must be always "direct" (`DataField` element).

If you want to do extra processing on "direct" target fields, then you should use `OutputField` elements.

By looking at your latest PMML, then I can make the following observations/suggestions:
1. Collapse `<field name>` and `<field name>-missing` into a single `DerivedField` element: "if <field value> is missing return 0, otherwise return <field value>". Alternatively, you could use the `MiiningField@missingValueReplacement` attribute to replace missing values with `0` values.
2. It should be possible to encode One-vs-Rest models using the "model chain" approach. At the top level define `MiningModel/Segmentation@multipleModelMethod="modelChain"`, then add one child model element for each One-vs-Rest pair, and then append a final `RegressionModel` element that performs the `simplemax` normalization over the earlier One-vs-Rest partial scores.

You may want to see how One-vs-Rest is implemented in SkLearn2PMML/JPMML-SkLearn.

**Comment by cheesinglee** [comment]
> Collapse <field name> and <field name>-missing into a single DerivedField element: "if <field value> is missing return 0, otherwise return <field value>". Alternatively, you could use the MiiningField@missingValueReplacement attribute to replace missing values with 0 values.

For each input field, we generate additional indicator variables for missing values. These indicators are used in the regression and have coefficients fit to them, so I believe they need to remain separate fields in the PMML.

> You may want to see how One-vs-Rest is implemented in SkLearn2PMML/JPMML-SkLearn.

Playing with `sklearn2pmml` was quite illuminating. In particular, I realized that the submodels don't need to be classification models and so there is no need to provide binarized targets. I think I'm on track now thanks!
