### ISSUE TITLE
Serialization error with Kryo

### ISSUE THREAD

**Issue by Szancode** [jpmml/jpmml-evaluator#114]
I'm trying to load a model converted by sklearn2pmml, which will be Serialized in a spark program with serialization tool Kryo. But, it encountered a problem just show as below. 
I found some other serialization issues like #10 and #103, but they look like a different problem.
My Code just like this:
```
public class RecallWeight {
    private static final Logger LOG = LoggerFactory.getLogger(RecallWeight.class);
    private Map<String, Integer> wordIndex;
    private List<double[]> vector;
    private ModelEvaluator<? extends Model> modelEvaluator;
    private double[] dset_data;

    RecallWeight(BufferedReader w2vReader) throws IOException {
        try (InputStream input = this.getClass().getResourceAsStream("/test.pmml")) {
            PMML pmml = PMMLUtil.unmarshal(input);
            this.modelEvaluator = ModelEvaluatorFactory.newInstance().newModelEvaluator(pmml);
        } catch (JAXBException | SAXException e) {
            throw new IOException(e);
        }
        long s_time = System.currentTimeMillis();
        Embedding embedding = new Embedding(w2vReader);
        long e_time = System.currentTimeMillis();
        LOG.info("w2v file loaded, elapsed(ms) " + (e_time - s_time));
        this.wordIndex = embedding.wordIndex;
        this.vector = embedding.indexVector;
    }
```
Strangely, when I change the "modelEvaluator" with a "static" modifier, it works well. But, I think it's an ugly solution.
So, any advice can be given? Thx.

jpmml-evaluator: 1.4.1

```
com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): org.jpmml.evaluator.regression.RegressionModelEvaluator**
Serialization trace:
modelEvaluator (com.###.RecallWeight)
recallWeight (com.###.ZQueryParser)

	at com.esotericsoftware.kryo.Kryo$DefaultInstantiatorStrategy.newInstantiatorOf(Kryo.java:1228)
	at com.esotericsoftware.kryo.Kryo.newInstantiator(Kryo.java:1049)
	at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1058)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.create(FieldSerializer.java:547)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:523)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:761)
	at com.###.ZQueryParserTest.testKryoSerializable(ZQueryParserTest.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by vruusmann** [comment]
All model evaluator classes must be parameterized with a pair of `org.dmg.pmml.PMML` and `org.dmg.pmml.Model` objects during construction.

So, a non-arg constructor, which Kryo is looking for, would violate this design decision/requirement.
