### ISSUE TITLE
Exception while running pmml-example-evaluator 

### ISSUE THREAD

**Issue by tanroopdhillon** [jpmml/jpmml-evaluator#139]
Error: A JNI error has occurred, please check your installation and try again
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/beust/jcommander/ParameterException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.beust.jcommander.ParameterException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```

**Comment by vruusmann** [comment]
The directory `pmml-evaluator-example` contains sample command-line applications. If you build the JPMML-Evaluator project from source checkout, then the build produces two files:

- `/pmml-evaluator-example/target/pmml-evaluator-example-1.4-SNAPSHOT.jar` - library JAR file, approx size 30 kB.
- `/pmml-evaluator-example/target/pmml-evaluator-example-executable-1.4-SNAPSHOT.jar` - executable uber-JAR file, approx size 15 MB.

You're probably trying to execute the first file (does not contain `com.beust.*` classes). However, you should be executing the second file (contains all transitive dependency classes, including all `com.beust.*` classes).

Better yet, it's possible to download executable uber-JAR files (for quick testing purposes) from this page:
https://github.com/jpmml/jpmml-evaluator/releases
