### ISSUE TITLE
Duplicate value Exception for Tree Model using Iris Data --- execution

### ISSUE THREAD

**Issue by Tulasamma** [jpmml/jpmml-evaluator#19]
Hi,
am new to this, while i have execute below exception is occuring.
R-PMML tree model getting exception,

used below line for execution:
D:\JPMML\jpmml-evaluator-master\pmml-evaluator-example>java -cp target/example-1.2-SNAPSHOT.jar org.jpmml.evaluator.EvaluationExample --model D:\JPMML\Test\pmml\IrisTree.pmml --input D:\JPMML\Test\csv\Iris.csv --output D:\JPMML\Test\output\TreeOutput.csv
 
Exception in thread "main" org.jpmml.evaluator.DuplicateValueException: class
        at org.jpmml.evaluator.EvaluationContext.declare(EvaluationContext.java:91)
        at org.jpmml.evaluator.OutputUtil.evaluate(OutputUtil.java:330)
        at org.jpmml.evaluator.TreeModelEvaluator.evaluate(TreeModelEvaluator.java:93)
        at org.jpmml.evaluator.ModelEvaluator.evaluate(ModelEvaluator.java:406)
        at org.jpmml.evaluator.EvaluationExample.execute(EvaluationExample.java:261)
        at org.jpmml.evaluator.Example.execute(Example.java:60)
        at org.jpmml.evaluator.EvaluationExample.main(EvaluationExample.java:127)

**Comment by vruusmann** [comment]
Your PMML document is "structurally" invalid. Apparently, the field `class` is defined in more than one place (most likely first as a target field (via `DataField` element) and then as an output field (via `OutputField` element)). This is a violation of [PMML field scoping rules] (http://dmg.org/pmml/v4-2-1/FieldScope.html).

If you can share your PMML document will me I'll be happy to point out the exact location of those field definitions. I would generally advise you against playing with DMG.org's example PMML documents, because a great number of them are invalid/broken. You should check out JPMML-Evaluator's example PMML documents that are typically located inside `src/test/resources/pmml` subdirectories.

Closing this issue as invalid, because the JPMML-Evaluator library is behaving correctly here.
