### ISSUE TITLE
How do pre-processing in pmml?

### ISSUE THREAD

**Issue by Jaaaaaay** [jpmml/jpmml-evaluator#193]
In my case, I have some raw features for input, but I did some easypre-processing (like A+B or if A > b then 1 else 0) with python, Now I want to do the same thing in pmml, TransformationDictionary was used here, Some errors happened.
````java
Traceback (most recent call last):
  File "/Users/tangjie/PycharmProjects/DYCJR/process/verify_pmml.py", line 21, in <module>
    inputFields = evaluator.getInputFields()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jpmml_evaluator/__init__.py", line 66, in getInputFields
    self.inputFields = _initModelFields(self.backend, self.javaEvaluator.getInputFields())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jpmml_evaluator/__init__.py", line 52, in _initModelFields
    return [ModelField(backend, javaModelFields.get(i)) for i in range(javaModelFields.size())]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jpmml_evaluator/__init__.py", line 52, in <listcomp>
    return [ModelField(backend, javaModelFields.get(i)) for i in range(javaModelFields.size())]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jpmml_evaluator/__init__.py", line 36, in __init__
    self.dataType = javaModelField.getDataType().value()
  File "jnius/jnius_export_class.pxi", line 857, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 937, in jnius.JavaMethod.call_method
  File "jnius/jnius_jvm_dlopen.pxi", line 91, in jnius.create_jnienv
jnius.JavaException: JVM exception occurred: Field "pre-processing feature name" is not defined org.jpmml.evaluator.MissingFieldException

````

**Comment by vruusmann** [comment]
> jnius.JavaException: JVM exception occurred: Field "pre-processing feature name" is not defined org.jpmml.evaluator.MissingFieldException

Looks like your manually crafted PMML markup is not quite correct - the definition of field `pre-processing feature name` cannot be found.

The [JPMML-Python](https://github.com/jpmml/jpmml-python) library provides `org.jpmml.python.ExpressionTranslator` and `org.jpmml.python.PredicateTranslator` components that can translate Python expressions and predicates (aka boolean expressions) to PMML.

If you're new to PMML, then it's advisable to use those Python-to-PMML translators for quick prototyping.

If you're mostly training models in Scikit-Learn, then you may take a look at the `sklearn2pmml.preprocessing.ExpressionTransformer` transformer class.
