### ISSUE TITLE
MissingFieldException for IsolationForest after jpmml-evaluator-1.4.14

### ISSUE THREAD

**Issue by jinlong-hao** [jpmml/jpmml-evaluator#205]
When i upgrade jpmml-evaluator from 1.4.11 to 1.5.3， I got MissingFieldException when evaluate a IsolationForest model. 
I tried every version after 1.4.11, and found that this error appear between 1.4.15-1.5.4.

The exception message stack  is:
```
org.jpmml.evaluator.MissingFieldException: Field "rawAnomalyScore" is not defined
	at org.jpmml.evaluator.ModelEvaluationContext.resolve(ModelEvaluationContext.java:149) ~[pmml-evaluator-1.5.3.jar:na]
	at org.jpmml.evaluator.EvaluationContext.evaluate(EvaluationContext.java:103) ~[pmml-evaluator-1.5.3.jar:na]
	at org.jpmml.evaluator.ExpressionUtil.evaluateFieldRef(ExpressionUtil.java:245) ~[pmml-evaluator-1.5.3.jar:na]
	at org.jpmml.evaluator.ExpressionUtil.evaluateExpression(ExpressionUtil.java:166) ~[pmml-evaluator-1.5.3.jar:na]
	at org.jpmml.evaluator.ExpressionUtil.evaluate(ExpressionUtil.java:152) ~[pmml-evaluator-1.5.3.jar:na]
	at org.jpmml.evaluator.ExpressionUtil.evaluateApply(ExpressionUtil.java:449) ~[pmml-evaluator-1.5.3.jar:na]
	at org.jpmml.evaluator.ExpressionUtil.evaluateExpression(ExpressionUtil.java:190) ~[pmml-evaluator-1.5.3.jar:na]
	at org.jpmml.evaluator.ExpressionUtil.evaluate(ExpressionUtil.java:152) ~[pmml-evaluator-1.5.3.jar:na]
	at org.jpmml.evaluator.ExpressionUtil.evaluateExpressionContainer(ExpressionUtil.java:84) ~[pmml-evaluator-1.5.3.jar:na]
	at org.jpmml.evaluator.OutputUtil.evaluate(OutputUtil.java:251) ~[pmml-evaluator-1.5.3.jar:na]
	at org.jpmml.evaluator.ModelEvaluator.evaluateInternal(ModelEvaluator.java:498) ~[pmml-evaluator-1.5.3.jar:na]
	at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluateInternal(MiningModelEvaluator.java:242) ~[pmml-evaluator-1.5.3.jar:na]
	at org.jpmml.evaluator.ModelEvaluator.evaluate(ModelEvaluator.java:306) ~[pmml-evaluator-1.5.3.jar:na]
```

**Comment by vruusmann** [comment]
The JPMML-SkLearn project contains an integration test for the `IsolationForest` model type here:
https://github.com/jpmml/jpmml-sklearn/blob/1.6.7/src/test/resources/main.py#L838
https://github.com/jpmml/jpmml-sklearn/blob/1.6.7/src/test/java/org/jpmml/sklearn/OutlierDetectorTest.java#L26-L29

It appears to work fine with all JPMML-Evaluator versions in range [1.4.X, 1.5.X].

Can you extract your `IsolationForest` model into a reproducible test case (model in PMML data format plus a couple of data records in CSV data format), and share it with me? I'd like to see the PMML markup, and run it locally to better understand this field name resolution issue.

If you prefer, you may send this test case material to my e-mail. I'm working on the JPMML-Evaluator 1.5.5 version right now, so if you're quick, we can have it fixed fairly quickly.

**Comment by jinlong-hao** [comment]
@vruusmann  I just only have the pmml file: 

[model.txt](https://github.com/jpmml/jpmml-evaluator/files/5507449/model.txt)

**Comment by vruusmann** [comment]
I don't see nothing structurally wrong with the sample PMML file - the `rawAnomalyScore` output field is properly defined, and will be always evaluated as the first step of the `/PMML/MiningModel/Output` element.

Just to prove, I generated a sample input CSV file (attached as `input.csv`), and it evaluates fine:
```
$ java -jar pmml-evaluator-example/target/pmml-evaluator-example-executable-1.5-SNAPSHOT.jar --model model.txt --input input.txt --output output.txt
```

One explanation for a `MissingFieldException` (in the context of output fields) is that perhaps your model evaluated to a missing value (`null`)? In that case the evaluation context is not populated with a new entry - field looks undeclared/missing to whoever may later need it.

Of course, the above doesn't quite explain why the field is found with older versions, and not with newer ones. That's why I'm asking for a reproducible test case. Right now, I don't see anything wrong.

[input.txt](https://github.com/jpmml/jpmml-evaluator/files/5508331/input.txt)
