### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by ayushpatidar** [jpmml/jpmml-evaluator#245]
Caused by: java.lang.NoClassDefFoundError: jakarta/xml/bind/JAXBContext
	at org.jpmml.model.JAXBUtil.getContext(JAXBUtil.java:106)
	at org.jpmml.model.JAXBUtil.createUnmarshaller(JAXBUtil.java:153)
	at org.jpmml.evaluator.LoadingModelEvaluatorBuilder.load(LoadingModelEvaluatorBuilder.java:143)
	at org.jpmml.evaluator.LoadingModelEvaluatorBuilder.load(LoadingModelEvaluatorBuilder.java:132)
	at org.jpmml.evaluator.LoadingModelEvaluatorBuilder.load(LoadingModelEvaluatorBuilder.java:120)

java version "1.8.0_321"

**Comment by vruusmann** [comment]
Fix your classpath:
https://github.com/jpmml/jpmml-evaluator#installation
