### ISSUE TITLE
java.lang.IllegalArgumentException: Name cannot be empty

### ISSUE THREAD

**Issue by ddiddi** [jpmml/jpmml-evaluator#260]
When we use the command
` java -jar pmml-evaluator-example-executable-1.5.16.jar --model model_name.pmml --input data_name.csv --output /dev/null --optimize --intern --loop 1000`
As per benchmarking transpiler instructions it returns an error expected name.
Where does this name property need to be edited? 
`Exception in thread "main" java.lang.IllegalArgumentException: Name cannot be empty
	at org.dmg.pmml.FieldName.create(FieldName.java:89)
	at org.jpmml.evaluator.testing.BatchUtil.parseRecords(BatchUtil.java:151)
	at org.jpmml.evaluator.example.EvaluationExample.execute(EvaluationExample.java:276)
	at org.jpmml.evaluator.example.Example.execute(Example.java:92)
	at org.jpmml.evaluator.example.EvaluationExample.main(EvaluationExample.java:262)`

**Comment by vruusmann** [comment]
An empty string `""` is not a valid field name. End of story.
