### ISSUE TITLE
org.jpmml.evaluator.EvaluationException

### ISSUE THREAD

**Issue by aminaaslam** [jpmml/jpmml-evaluator#30]
I am working on RulesInduction model and JPMML keeps complaining about this file whose contents i have copied in this issue. I am not able to figure out what is the problem. Please help me with it.

Exception:
```
org.jpmml.evaluator.EvaluationException
	at org.jpmml.evaluator.CategoricalValue.compareToString(CategoricalValue.java:39)
	at org.jpmml.evaluator.FieldValue.compareTo(FieldValue.java:143)
	at org.jpmml.evaluator.PredicateUtil.evaluateSimplePredicate(PredicateUtil.java:131)
	at org.jpmml.evaluator.PredicateUtil.evaluatePredicate(PredicateUtil.java:63)
	at org.jpmml.evaluator.PredicateUtil.evaluate(PredicateUtil.java:51)
	at org.jpmml.evaluator.PredicateUtil.evaluateCompoundPredicateInternal(PredicateUtil.java:200)
	at org.jpmml.evaluator.PredicateUtil.evaluateCompoundPredicate(PredicateUtil.java:168)
	at org.jpmml.evaluator.PredicateUtil.evaluatePredicate(PredicateUtil.java:71)
	at org.jpmml.evaluator.PredicateUtil.evaluate(PredicateUtil.java:51)
	at org.jpmml.evaluator.RuleSetModelEvaluator.evaluateRule(RuleSetModelEvaluator.java:190)
	at org.jpmml.evaluator.RuleSetModelEvaluator.evaluateRules(RuleSetModelEvaluator.java:216)
	at org.jpmml.evaluator.RuleSetModelEvaluator.evaluateClassification(RuleSetModelEvaluator.java:109)
	at org.jpmml.evaluator.RuleSetModelEvaluator.evaluate(RuleSetModelEvaluator.java:84)
	at org.jpmml.evaluator.ModelEvaluator.evaluate(ModelEvaluator.java:406)
	at com.norkom.blake.pmml.IrepRuleTest.makePredictions(IrepRuleTest.java:177)
	at com.norkom.blake.pmml.IrepRuleTest.testRules(IrepRuleTest.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

PMML file:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<PMML xmlns="http://www.dmg.org/PMML-4_2">
    <DataDictionary numberOfFields="13">
        <DataField name="TransactionType" optype="categorical" dataType="string">
            <Value value="ATM"/>
            <Value value="Point of Sale"/>
            <Value value="Point of Sale BGC"/>
            <Value value="Term Deposit Post Office"/>
        </DataField>
        <DataField name="Amount" optype="continuous" dataType="double"/>
        <DataField name="CreditOrDebit" optype="categorical" dataType="string">
            <Value value="Credit"/>
            <Value value="Debit"/>
        </DataField>
        <DataField name="Currency" optype="categorical" dataType="string">
            <Value value="DOLLAR"/>
            <Value value="EUR"/>
        </DataField>
        <DataField name="POSAmount3Days.acc.day.present" optype="continuous" dataType="double"/>
        <DataField name="POSAmount3Days.acc.day.total" optype="continuous" dataType="double"/>
        <DataField name="POSAmount4hr.acc.hour4" optype="continuous" dataType="double"/>
        <DataField name="POSAmount60Mins.acc.minute60" optype="continuous" dataType="double"/>
        <DataField name="POSCount3Days.cnt.day.present" optype="continuous" dataType="double"/>
        <DataField name="POSCount3Days.cnt.day.total" optype="continuous" dataType="double"/>
        <DataField name="POSCount4hr.cnt.hour4" optype="continuous" dataType="double"/>
        <DataField name="POSCount60Mins.cnt.minute60" optype="continuous" dataType="double"/>
        <DataField name="Fraud" optype="categorical" dataType="double">
            <Value value="0.0"/>
            <Value value="1.0"/>
        </DataField>
    </DataDictionary>
    <RuleSetModel modelName="RulesSetModel" functionName="classification">
        <MiningSchema>
            <MiningField name="TransactionType"/>
            <MiningField name="Amount"/>
            <MiningField name="CreditOrDebit"/>
            <MiningField name="Currency"/>
            <MiningField name="POSAmount3Days.acc.day.present"/>
            <MiningField name="POSAmount3Days.acc.day.total"/>
            <MiningField name="POSAmount4hr.acc.hour4"/>
            <MiningField name="POSAmount60Mins.acc.minute60"/>
            <MiningField name="POSCount3Days.cnt.day.present"/>
            <MiningField name="POSCount3Days.cnt.day.total"/>
            <MiningField name="POSCount4hr.cnt.hour4"/>
            <MiningField name="POSCount60Mins.cnt.minute60"/>
            <MiningField name="Fraud" usageType="target"/>
        </MiningSchema>
        <RuleSet recordCount="5152.0" nbCorrect="5033.0" defaultScore="0" defaultConfidence="0.0">
            <RuleSelectionMethod criterion="firstHit"/>
            <SimpleRule id="Rule0" score="1.0" recordCount="95.0" nbCorrect="89.0" confidence="0.9325842696629213">
                <CompoundPredicate booleanOperator="and">
                    <SimplePredicate field="POSAmount4hr.acc.hour4" operator="greaterOrEqual" value="104.1"/>
                    <SimplePredicate field="POSAmount4hr.acc.hour4" operator="greaterOrEqual" value="182.63"/>
                </CompoundPredicate>
                <ScoreDistribution value="0.0" recordCount="6.0"/>
                <ScoreDistribution value="1.0" recordCount="89.0"/>
            </SimpleRule>
            <SimpleRule id="Rule1" score="1.0" recordCount="8.0" nbCorrect="8.0" confidence="1.0">
                <CompoundPredicate booleanOperator="and">
                    <SimplePredicate field="POSAmount4hr.acc.hour4" operator="greaterOrEqual" value="80.0"/>
                    <SimplePredicate field="Amount" operator="greaterOrEqual" value="104.1"/>
                    <SimplePredicate field="Amount" operator="lessOrEqual" value="104.16"/>
                </CompoundPredicate>
                <ScoreDistribution value="0.0" recordCount="0.0"/>
                <ScoreDistribution value="1.0" recordCount="8.0"/>
            </SimpleRule>
            <SimpleRule id="Rule2" score="1.0" recordCount="16.0" nbCorrect="13.0" confidence="0.7692307692307693">
                <CompoundPredicate booleanOperator="and">
                    <SimplePredicate field="POSAmount60Mins.acc.minute60" operator="greaterOrEqual" value="37.64"/>
                    <SimplePredicate field="POSAmount3Days.acc.day.present" operator="greaterOrEqual" value="148.57"/>
                    <SimplePredicate field="TransactionType" operator="greaterOrEqual" value="13.0"/>
                    <SimplePredicate field="POSAmount3Days.acc.day.present" operator="greaterOrEqual" value="261.19"/>
                </CompoundPredicate>
                <ScoreDistribution value="0.0" recordCount="3.0"/>
                <ScoreDistribution value="1.0" recordCount="13.0"/>
            </SimpleRule>
            <SimpleRule id="Rule3" score="1.0" recordCount="8.0" nbCorrect="6.0" confidence="0.6666666666666666">
                <CompoundPredicate booleanOperator="and">
                    <SimplePredicate field="POSAmount4hr.acc.hour4" operator="greaterOrEqual" value="90.95"/>
                    <SimplePredicate field="Amount" operator="greaterOrEqual" value="147.57"/>
                </CompoundPredicate>
                <ScoreDistribution value="0.0" recordCount="2.0"/>
                <ScoreDistribution value="1.0" recordCount="6.0"/>
            </SimpleRule>
            <SimpleRule id="Rule4" score="1.0" recordCount="4.0" nbCorrect="3.0" confidence="0.6666666666666666">
                <CompoundPredicate booleanOperator="and">
                    <SimplePredicate field="POSAmount4hr.acc.hour4" operator="greaterOrEqual" value="90.95"/>
                    <SimplePredicate field="POSAmount60Mins.acc.minute60" operator="lessOrEqual" value="90.95"/>
                </CompoundPredicate>
                <ScoreDistribution value="0.0" recordCount="1.0"/>
                <ScoreDistribution value="1.0" recordCount="3.0"/>
            </SimpleRule>
        </RuleSet>
    </RuleSetModel>
</PMML>
```

**Comment by vruusmann** [comment]
This is a valid exception, because it is not permitted to use comparison operators `lessThan`, `lessOrEqual`, `greaterOrEqual` or `greaterThan` with categorical field values.

You have a categorical input field "TransactionType":
```
<DataField name="TransactionType" optype="categorical" dataType="string">
	<Value value="ATM"/>
	<Value value="Point of Sale"/>
	<Value value="Point of Sale BGC"/>
	<Value value="Term Deposit Post Office"/>
</DataField>
```

But you're using it in a simple predicate like this:
```
<SimplePredicate field="TransactionType" operator="greaterOrEqual" value="13.0"/>
```
