### ISSUE TITLE
Performance issues with 'at org.jpmml.evaluator.ModelEvaluator.getInputFields(ModelEvaluator.java:207)' for multiple threads #2

### ISSUE THREAD

**Issue by GRaote** [jpmml/jpmml-evaluator#39]
With around ~900 input fields of type double in my model , most of the threads waste time (28% of the execution time ) in this method 'at org.jpmml.evaluator.ModelEvaluator.getInputFields(ModelEvaluator.java:207)'which is called everytime per thread execution.

Same method is called while creating the arguments per thread , I made a common inputField over there which solved that issues but again for evaluate , it is calling that method and affecting the performance.

Can we pass inputFields in evaluate method along with arguments , this could save 28% of the execution time ? This would require changing arguments everywhere.

Thread Dump:
    at org.jpmml.evaluator.ModelEvaluator.createInputFields(ModelEvaluator.java:397)
    at org.jpmml.evaluator.ModelEvaluator.getInputFields(ModelEvaluator.java:207)
    at org.jpmml.evaluator.mining.MiningModelEvaluator.createSegmentHandler(MiningModelEvaluator.java:600)
    at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluateSegmentation(MiningModelEvaluator.java:367)
    at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluateClassification(MiningModelEvaluator.java:240)
    at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:207)
    at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:185)

**Comment by vruusmann** [comment]
The method `ModelManager#createInputFields()` is executed (at most-) once over the lifetime of a model evaluator instance.
