### ISSUE TITLE
org.dmg.pmml.MiningField.getOptype()Lorg/dmg/pmml/OpType

### ISSUE THREAD

**Issue by mahuacai** [jpmml/jpmml-evaluator#41]
16/12/12 19:04:26 WARN scheduler.TaskSetManager: Lost task 0.0 in stage 1.0 (TID 2, byd0158): java.lang.NoSuchMethodError: org.dmg.pmml.MiningField.getOptype()Lorg/dmg/pmml/OpType;
	at org.jpmml.evaluator.ArgumentUtil.isOutlier(ArgumentUtil.java:153)
	at org.jpmml.evaluator.ArgumentUtil.prepare(ArgumentUtil.java:69)
	at org.jpmml.evaluator.ModelEvaluator.prepare(ModelEvaluator.java:110)
	at org.jpmml.spark.PMMLTransformer$2.apply(PMMLTransformer.java:120)
	at org.jpmml.spark.PMMLTransformer$2.apply(PMMLTransformer.java:110)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply119245_186$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.execution.Project$$anonfun$1$$anonfun$apply$1.apply(basicOperators.scala:51)
	at org.apache.spark.sql.execution.Project$$anonfun$1$$anonfun$apply$1.apply(basicOperators.scala:49)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:312)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
	at scala.collection.AbstractIterator.to(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$5.apply(SparkPlan.scala:212)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$5.apply(SparkPlan.scala:212)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mahuacai** [comment]
/etc/spark-1.6.0-bin-hadoop2.6/bin/spark-submit \
--class com.totaldata.predict.UserAgePredictTotalData \
--jars /home/censj/spark_new/ml/lib/hbase-client-1.2.4.jar,/home/censj/spark_new/ml/lib/hbase-common-1.2.4.jar,/home/censj/spark_new/ml/lib/hbase-server-1.2.4.jar,/home/censj/lib/hbase-hadoop2-compat-0.98.7-hadoop2.jar,/home/censj/lib/hbase-hadoop-compat-1.1.2.jar,/home/censj/lib/metrics-core-2.2.0.jar,/home/censj/spark_new/ml/lib/hbase-protocol-1.2.4.jar,/usr/hdp/2.3.0.0-2557/hbase/lib/guava-12.0.1.jar,/home/censj/lib/htrace-core-3.2.0-incubating.jar,/home/censj/spark_new/ml/lib/gitlab-jira-integration-application-0.3.1.jar,/home/censj/spark_new/ml/lib/pmml-evaluator-1.1.15.jar,/home/censj/spark_new/ml/lib/pmml-model-1.1.15.jar,/home/censj/spark_new/ml/lib/pmml-manager-1.1.15.jar

**Comment by mahuacai** [comment]
pmml-evaluator-1.1.15.jar this version can you help me?

**Comment by vruusmann** [comment]
You need to fix your application classpath. Specifically, you need to apply shading to JPMML-Model library classes as detailed in the README.md file of the JPMML-Spark library.

This has been explained over and over in many places.
