### ISSUE TITLE
 Lost task 0.0 in stage 1.0 (TID 2, byd0158): org.jpmml.evaluator.InvalidFeatureException (at or around line 5759): Target

### ISSUE THREAD

**Issue by mahuacai** [jpmml/jpmml-evaluator#42]
16/12/13 14:58:12 WARN scheduler.TaskSetManager: Lost task 0.0 in stage 1.0 (TID 2, byd0158): org.jpmml.evaluator.InvalidFeatureException (at or around line 5759): Target
	at org.jpmml.evaluator.IndexableUtil.ensureKey(IndexableUtil.java:81)
	at org.jpmml.evaluator.IndexableUtil.buildMap(IndexableUtil.java:64)
	at org.jpmml.evaluator.ModelEvaluator$7.load(ModelEvaluator.java:586)
	at org.jpmml.evaluator.ModelEvaluator$7.load(ModelEvaluator.java:582)
	at com.shaded.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
	at com.shaded.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
	at com.shaded.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
	at com.shaded.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	at com.shaded.google.common.cache.LocalCache.get(LocalCache.java:3953)
	at com.shaded.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
	at com.shaded.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)
	at org.jpmml.evaluator.CacheUtil.getValue(CacheUtil.java:50)
	at org.jpmml.evaluator.ModelEvaluator.<init>(ModelEvaluator.java:139)
	at org.jpmml.evaluator.MiningModelEvaluator.<init>(MiningModelEvaluator.java:79)
	at org.jpmml.evaluator.ModelEvaluatorFactory.newModelManager(ModelEvaluatorFactory.java:66)
	at org.jpmml.evaluator.MiningModelEvaluator.createSegmentHandler(MiningModelEvaluator.java:559)
	at org.jpmml.evaluator.MiningModelEvaluator.evaluateSegmentation(MiningModelEvaluator.java:355)
	at org.jpmml.evaluator.MiningModelEvaluator.evaluateClassification(MiningModelEvaluator.java:223)
	at org.jpmml.evaluator.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:190)
	at org.jpmml.evaluator.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:167)
	at org.jpmml.evaluator.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:162)
	at org.jpmml.spark.PMMLTransformer$2.apply(PMMLTransformer.java:128)
	at org.jpmml.spark.PMMLTransformer$2.apply(PMMLTransformer.java:113)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.evalExpr2$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.execution.Project$$anonfun$1$$anonfun$apply$1.apply(basicOperators.scala:51)
	at org.apache.spark.sql.execution.Project$$anonfun$1$$anonfun$apply$1.apply(basicOperators.scala:49)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:312)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
	at scala.collection.AbstractIterator.to(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$5.apply(SparkPlan.scala:212)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$5.apply(SparkPlan.scala:212)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mahuacai** [comment]
now I Use 
 <dependency>
            <groupId>org.jpmml</groupId>
            <artifactId>pmml-evaluator</artifactId>
            <version>1.2.15</version>
        </dependency>

**Comment by mahuacai** [comment]
16/12/13 14:58:12 WARN scheduler.TaskSetManager: Lost task 0.0 in stage 1.0 (TID 2, byd0158): org.jpmml.evaluator.InvalidFeatureException (at or around line 5759): Target
	at org.jpmml.evaluator.IndexableUtil.ensureKey(IndexableUtil.java:81)
	at org.jpmml.evaluator.IndexableUtil.buildMap(IndexableUtil.java:64)
	at org.jpmml.evaluator.ModelEvaluator$7.load(ModelEvaluator.java:586)
	at org.jpmml.evaluator.ModelEvaluator$7.load(ModelEvaluator.java:582)
	at com.shaded.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
	at com.shaded.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
	at com.shaded.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
	at com.shaded.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	at com.shaded.google.common.cache.LocalCache.get(LocalCache.java:3953)
	at com.shaded.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
	at com.shaded.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)
	at org.jpmml.evaluator.CacheUtil.getValue(CacheUtil.java:50)
	at org.jpmml.evaluator.ModelEvaluator.<init>(ModelEvaluator.java:139)
	at org.jpmml.evaluator.MiningModelEvaluator.<init>(MiningModelEvaluator.java:79)
	at org.jpmml.evaluator.ModelEvaluatorFactory.newModelManager(ModelEvaluatorFactory.java:66)
	at org.jpmml.evaluator.MiningModelEvaluator.createSegmentHandler(MiningModelEvaluator.java:559)
	at org.jpmml.evaluator.MiningModelEvaluator.evaluateSegmentation(MiningModelEvaluator.java:355)
	at org.jpmml.evaluator.MiningModelEvaluator.evaluateClassification(MiningModelEvaluator.java:223)
	at org.jpmml.evaluator.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:190)
	at org.jpmml.evaluator.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:167)
	at org.jpmml.evaluator.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:162)
	at org.jpmml.spark.PMMLTransformer$2.apply(PMMLTransformer.java:128)
	at org.jpmml.spark.PMMLTransformer$2.apply(PMMLTransformer.java:113)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.evalExpr2$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.execution.Project$$anonfun$1$$anonfun$apply$1.apply(basicOperators.scala:51)
	at org.apache.spark.sql.execution.Project$$anonfun$1$$anonfun$apply$1.apply(basicOperators.scala:49)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:312)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
	at scala.collection.AbstractIterator.to(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$5.apply(SparkPlan.scala:212)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$5.apply(SparkPlan.scala:212)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by vruusmann** [comment]
Exception `org.jpmml.evaluator.InvalidFeatureException` indicates that the PMML document is structurally invalid. Please fix it (something about the Target element on line 5759), and try again.

**Comment by mahuacai** [comment]
this PMML file   line 5759
                                       <Targets>
                                                <Target rescaleConstant="0.5"/>
                                        </Targets>

**Comment by vruusmann** [comment]
The above is a PMML 4.3-style Target element, which refers to the default target field (ie. the `Target@field` attribute is not specified).

A PMML 4.2 engine such as JPMML-Evaluator 1.2.X will reject it as invalid. A PMML 4.3 engine such as JPMML-Evaluator 1.3.X will accept it.

Looks like your Spark application depends on a wrong JPMML-Evaluator library version. Again, please see the README.md files of JPMML-Evaluator and JPMML-Spark projects. It's all explained there - please spend 5 minutes reading the documentation, instead of opening a series of invalid GitHub issues.
