### ISSUE TITLE
InvalidFeatureException: MiningField

### ISSUE THREAD

**Issue by aminaaslam** [jpmml/jpmml-evaluator#49]
Hi Villu,
I have also attached my file 

[PMML.txt](https://github.com/jpmml/jpmml-evaluator/files/828075/PMML.txt)

I am generating PMML for NeuralNetwork but when i use the evaluator it keeps throwing this exception.
```
org.jpmml.evaluator.InvalidFeatureException: MiningField
	at org.jpmml.evaluator.IndexableUtil.buildMap(IndexableUtil.java:72)
	at org.jpmml.evaluator.IndexableUtil.buildMap(IndexableUtil.java:61)
	at org.jpmml.evaluator.ModelEvaluator$4.load(ModelEvaluator.java:688)
	at org.jpmml.evaluator.ModelEvaluator$4.load(ModelEvaluator.java:684)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
	at org.jpmml.evaluator.CacheUtil.getValue(CacheUtil.java:51)
	at org.jpmml.evaluator.ModelEvaluator.<init>(ModelEvaluator.java:128)
	at org.jpmml.evaluator.neural_network.NeuralNetworkEvaluator.<init>(NeuralNetworkEvaluator.java:90)
	at org.jpmml.evaluator.neural_network.NeuralNetworkEvaluator.<init>(NeuralNetworkEvaluator.java:86)
	at com.baesystems.ai.analytics.smile.pmml.NeuralNetworkPMMLTest.createEvaluator(NeuralNetworkPMMLTest.java:130)
	at com.baesystems.ai.analytics.smile.pmml.NeuralNetworkPMMLTest.testLeastMeanSqaures(NeuralNetworkPMMLTest.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by vruusmann** [comment]
The topmost stacktrace element (`at org.jpmml.evaluator.IndexableUtil.buildMap(IndexableUtil.java:72)`) points to the following sanity check:
https://github.com/jpmml/jpmml-evaluator/blob/master/pmml-evaluator/src/main/java/org/jpmml/evaluator/IndexableUtil.java#L72

It means that the `PMML/NeuralNetwork/MiningSchema` element contains duplicate `MiningField` elements. In this context, "duplicate" means that they have the same `MiningField@name` atrtribute value (as this is what is exposed via the `org.dmg.pmml.Indexable#getKey()` method).

In you PMML file, you have two `MiningField` elements for "Fraud". First, on line 151 (`<MiningField name="Fraud"/>`) and second, on line 247 (`<MiningField name="Fraud" usageType="predicted"/>`). It doesn't matter that they have different `MiningField@usageType` attribute values (`active` and `target`, respectively).

**Comment by vruusmann** [comment]
Also, it is interesting that your PMML file doesn't contain a `DataField` element for "Fraud" in its `/PMML/DataDictionary` element. This piece of information is definitely needed, the JPMML-Evaluator library would fail again (with a slightly different exception) if you re-evaluated it without correcting this structural deficiency first.

So, you should remove the first `MiningField` element declaration on line 151 (as by looking through the PMML file it becomes evident that this neural network model predicts "Fraud"), and then insert the following `DataField` element declaration:
```
<DataField name="Fraud" optype="categorical" dataType="string">
  <Value value="0"/>
  <Value value="1"/>
</DataField>
```

Also, since this is a classification-type model, it might be appropriate to introduce a `/PMML/NeuralNetwork/Output` element, which would output the probability distribution.

**Comment by aminaaslam** [comment]
thanks villu
