### ISSUE TITLE
Multiple Target Fields with KNN

### ISSUE THREAD

**Issue by infiton** [jpmml/jpmml-evaluator#64]
I trained a k nearest neighbours model on iris with R using https://cran.r-project.org/web/packages/neighbr/neighbr.pdf (this one has a pmml implemenation whereas the standard `knn` from `library(class)` does not)

and got the following PMML doc: 

[knn.txt](https://github.com/jpmml/jpmml-evaluator/files/1075951/knn.txt)

Running this against `java -cp target/example-1.3-SNAPSHOT.jar org.jpmml.evaluator.EvaluationExample --model knn.xml --input knn_in.csv --output knn_out.csv`

I get the following stack trace:

```
Exception in thread "main" org.jpmml.evaluator.EvaluationException
	at org.jpmml.evaluator.ModelEvaluator.getTargetField(ModelEvaluator.java:256)
	at org.jpmml.evaluator.ModelEvaluator.getTargetFieldName(ModelEvaluator.java:265)
	at org.jpmml.evaluator.OutputUtil.evaluate(OutputUtil.java:140)
	at org.jpmml.evaluator.nearest_neighbor.NearestNeighborModelEvaluator.evaluate(NearestNeighborModelEvaluator.java:193)
	at org.jpmml.evaluator.ModelEvaluator.evaluate(ModelEvaluator.java:384)
	at org.jpmml.evaluator.EvaluationExample.execute(EvaluationExample.java:300)
	at org.jpmml.evaluator.Example.execute(Example.java:86)
	at org.jpmml.evaluator.EvaluationExample.main(EvaluationExample.java:183)
```

which is pointing at: https://github.com/jpmml/jpmml-evaluator/blob/master/pmml-evaluator/src/main/java/org/jpmml/evaluator/ModelEvaluator.java#L256

I think that PMML knn can have multiple target fields 

> A k-NN model can have one or more target variables or no targets. When one or more targets are present, the predicted value is computed based on the target values of the nearest neighbors. When no targets are present, the model specifies a case ID variable for the training data. In this way, one can easily obtain the IDs of the K closest training cases (nearest neighbors).

**Comment by vruusmann** [comment]
Internally, there are multiple target values computed. This exception happens at the "outer surface", when preparing the results for presentation.

The convention is that a model should have at most one target field. 99.9% of real-life models adhere to this convention (eg. one can do `Evaluator#getTargetField()` instead of looping over `Evaluator#getTargetFields()`, which is 99.9% of time a singleton list).

The `neighbr` package is a niche package (published by Zementis very recently), that wants to do things its own way. I don't have time for handling its caprices.

Can't you just re-frame your problem so that a single target field would suffice?

**Comment by infiton** [comment]
Yah I agree that it's weird that KNN is the only model that supports more than one target field, but even in the spec they show multiple outputs

http://dmg.org/pmml/v4-3/KNN.html:

```xml
<PMML xmlns="http://www.dmg.org/PMML-4_3" version="4.3">
  <Header copyright="Copyright (c) 2011, DMG.org"/>
  <DataDictionary numberOfFields="6">
    <DataField name="petal length" optype="continuous" dataType="double"/>
    <DataField name="petal width" optype="continuous" dataType="double"/>
    <DataField name="sepal length" optype="continuous" dataType="double"/>
    <DataField name="sepal width" optype="continuous" dataType="double"/>
    <DataField name="species" optype="continuous" dataType="double"/>
    <DataField name="species_class" optype="categorical" dataType="string"/>     
  </DataDictionary>
  <NearestNeighborModel modelName="KNN IrisGardens" continuousScoringMethod="average" categoricalScoringMethod="majorityVote" numberOfNeighbors="3" functionName="mixed">
    <MiningSchema>
      <MiningField name="petal length"/>
      <MiningField name="petal width"/>
      <MiningField name="sepal length"/>
      <MiningField name="sepal width"/>
      <MiningField name="species" usageType="target"/>
      <MiningField name="species_class" usageType="target"/>         
    </MiningSchema>
    <Output>
      <OutputField targetField="species" dataType="double" feature="predictedValue" name="output_1" optype="continuous"/>  
      <OutputField targetField="species_class" dataType="string" feature="predictedValue" name="output_2" optype="categorical"/>
    </Output>     
    <TrainingInstances recordCount="149" fieldCount="6" isTransformed="false">
      <InstanceFields>
        <InstanceField field="petal length" column="petal_length"/>
        <InstanceField field="petal width" column="petal_width"/>
        <InstanceField field="sepal length" column="sepal_length"/>
        <InstanceField field="sepal width" column="sepal_width"/>
        <InstanceField field="species" column="target_species"/>
        <InstanceField field="species_class" column="target_class"/>            
      </InstanceFields>
      <InlineTable>
        <row>
          <sepal_length>4.9</sepal_length>
          <sepal_width>3.0</sepal_width>
          <petal_length>1.4</petal_length>
          <petal_width>0.2</petal_width>
          <target_species>10</target_species>
          <target_class>Iris-setosa</target_class>            
        </row>
        <row>
          <sepal_length>4.7</sepal_length>
          <sepal_width>3.2</sepal_width>
          <petal_length>1.3</petal_length>
          <petal_width>0.2</petal_width>
          <target_species>10</target_species>
          <target_class>Iris-setosa</target_class>                
        </row>
        <!-- ... -->
        <row>
          <sepal_length>7.0</sepal_length>
          <sepal_width>3.2</sepal_width>
          <petal_length>4.7</petal_length>
          <petal_width>1.24</petal_width>
          <target_species>20</target_species>
          <target_class>Iris-versicolor</target_class>                
        </row>
        <!-- ... -->
        <row>
          <sepal_length>6.3</sepal_length>
          <sepal_width>3.3</sepal_width>
          <petal_length>6.0</petal_length>
          <petal_width>2.5</petal_width>
          <target_species>30</target_species>
          <target_class>Iris-virginica</target_class>                
        </row>
      </InlineTable>
    </TrainingInstances>
    <ComparisonMeasure kind="distance">
      <squaredEuclidean/>
    </ComparisonMeasure>      
    <KNNInputs>
      <KNNInput field="petal length" compareFunction="absDiff"/>
      <KNNInput field="petal width" compareFunction="absDiff"/>
      <KNNInput field="sepal length" compareFunction="absDiff"/>
      <KNNInput field="sepal width" compareFunction="absDiff"/>
    </KNNInputs>
  </NearestNeighborModel>
</PMML>
```

**Comment by vruusmann** [comment]
I would argue that the `knn.txt` file that is attached to the opening comment is invalid PMML. Namely, the model has two target fields, but its `OutputField` element(s) do not specify which one of the two they targeting.

Current invalid markup:
```xml
<Output>
	<OutputField name="Predicted_Species" feature="predictedValue" dataType="string" optype="categorical"/>
	<OutputField name="Predicted_Petal.Width" feature="predictedValue" dataType="double" optype="continuous"/>
</Output>
```

Correct markup (note the added `OutputField@targetField` attributes):
```xml
<Output>
	<OutputField name="Predicted_Species" feature="predictedValue" targetField="Species" dataType="string" optype="categorical"/>
	<OutputField name="Predicted_Petal.Width" feature="predictedValue" targetField="Petal.Width" dataType="double" optype="continuous"/>
</Output>
```

**Comment by infiton** [comment]
yes I agree, the output from `neighbr` package is missing the `targetField` attribute. Adding that in still yields the same error, but at least with that markup the OutputEvaluator can know which predicted values to target

**Comment by vruusmann** [comment]
If the `targetField` attribute is specified for all `OutputField` elements, then the evaluation succeeds:
```xml
<Output>
	<OutputField name="Predicted_Species" feature="predictedValue" targetField="Species" dataType="string" optype="categorical"/>
	<OutputField name="Predicted_Petal.Width" feature="predictedValue" targetField="Petal.Width" dataType="double" optype="continuous"/>
	<OutputField name="neighbor1" feature="entityId" targetField="Species" dataType="string" optype="categorical" rank="1"/>
	<OutputField name="neighbor2" feature="entityId" targetField="Species" dataType="string" optype="categorical" rank="2"/>
	<OutputField name="neighbor3" feature="entityId" targetField="Species" dataType="string" optype="categorical" rank="3"/>
</Output>
```

For the last three output fields (`OutputField@feature="entityId"`) it doesn't matter if you reference the first or the second target field.

**Comment by infiton** [comment]
ok cool, thanks again for all your help on this. The R package is generating bad PMML!
