### ISSUE TITLE
CompundPredicate error with optimization

### ISSUE THREAD

**Issue by scf1984** [jpmml/jpmml-evaluator#68]
When evaluating a PMML with the 'optimize' flag on, a CompoundPredicate tag will cause an error, for example with the PMML example in http://dmg.org/pmml/v4-3/Scorecard.html:
```
Exception in thread "main" java.lang.UnsupportedOperationException
        at org.jpmml.model.visitors.AbstractImmutableList$1.set(AbstractImmutableList.java:98)
        at org.jpmml.model.visitors.PredicateFilterer.filterAll(PredicateFilterer.java:29)
        at org.jpmml.model.visitors.PredicateFilterer.visit(PredicateFilterer.java:49)
        at org.dmg.pmml.CompoundPredicate.accept(CompoundPredicate.java:193)
        at org.dmg.pmml.PMMLObject.traverse(PMMLObject.java:47)
        at org.dmg.pmml.scorecard.Attribute.accept(Attribute.java:250)
        at org.dmg.pmml.PMMLObject.traverse(PMMLObject.java:86)
        at org.dmg.pmml.scorecard.Characteristic.accept(Characteristic.java:247)
        at org.dmg.pmml.PMMLObject.traverse(PMMLObject.java:86)
        at org.dmg.pmml.scorecard.Characteristics.accept(Characteristics.java:158)
        at org.dmg.pmml.PMMLObject.traverse(PMMLObject.java:68)
        at org.dmg.pmml.scorecard.Scorecard.accept(Scorecard.java:688)
        at org.dmg.pmml.PMMLObject.traverse(PMMLObject.java:86)
        at org.dmg.pmml.PMML.accept(PMML.java:397)
        at org.jpmml.model.visitors.AbstractVisitor.applyTo(AbstractVisitor.java:272)
        at org.jpmml.evaluator.visitors.PredicateInterner.applyTo(PredicateInterner.java:82)
        at org.jpmml.evaluator.EvaluationExample.optimizePmml(EvaluationExample.java:233)
        at org.jpmml.evaluator.EvaluationExample.execute(EvaluationExample.java:268)
        at org.jpmml.evaluator.Example.execute(Example.java:86)
        at org.jpmml.evaluator.EvaluationExample.main(EvaluationExample.java:185)
```

**Comment by vruusmann** [comment]
I'm unable to reproduce this exception using the current `1.3-SNAPSHOT` version:
1. Copy & paste the model from http://dmg.org/pmml/v4-3/Scorecard.html to a new PMML file `scorecard.pmml`.
2. Evaluate this PMML file using the iris dataset (any other dataset would be equally good - just wanting to show that the scorecard model is executed N times, and that each and every execution produces the default prediction):
```
$ java -cp pmml-evaluator-example/target/example-1.3-SNAPSHOT.jar org.jpmml.evaluator.EvaluationExample --input pmml-rattle/src/test/resources/csv/Iris.csv --output scorecard.csv --model scorecard.pmml --sparse --intern --optimize
```

I think you're using an outdated version of JPMML-Evaluator. For example, the stacktrace suggests that the exception occurs inside method `EvaluationExample#optimizePmml()`, but there is no such method in the current version.

**Comment by vruusmann** [comment]
Having thought about this issue about some more, then I'm more than convinced that you're using an outdated JPMML-Evaluator version - the method `EvaluationExample#optimizePmml()`, which no longer exists, was performing `ArrayList` optimization before predicate interning. Some of the optimized `List` implementation classes such as `SingletonList` and `DoubletonList` are read-only data structures, hence the `UnsupportedOperationException` when trying to modify their contents.

Feel free to reopen this issue if you can reproduce this issue with the `1.3-SNAPSHOT` version.
