### ISSUE TITLE
Evaluator exception while using Count Vectorizer with Custom Transformer.

### ISSUE THREAD

**Issue by mohitbadwal** [jpmml/jpmml-evaluator#71]
If I use Count Vectorizer after a Custom transformer , I am unable to evaluate the pmml , although it gets created successfully . If I use only Count Vectorizer , it works fine. So , just to check I removed all logic from my Transformer class and simply returned the incoming value as a field value , I still get an exception.
This is my Dataframe Mapper when I use the Count Vectorizer with Custom function : 
`mapper = DataFrameMapper([('meta_email_subject',[CategoricalDomain(invalid_value_treatment = "as_missing", missing_value_replacement = "remittance"),
                                               CustomTransformFunctionGenerator(function='ParseText'),
                                               countVectorizer1])` 
And my custom function in java : 

```
public FieldValue evaluate(List<FieldValue> arguments) {
  // TODO Auto-generated method stub
  
  FieldValue field_attachment_link = arguments.get(0);
  
  if (field_attachment_link == null)
  {
   return field_attachment_link;
  }
  
  DataType dataType = field_attachment_link.getDataType();
  String result = null ;
  
  try{
                result = (String)field_attachment_link.getValue();
     } catch(Exception e)
  {
   throw new InvalidResultException(null);
  }
               FieldValue val = FieldValueUtil.create(dataType, OpType.CATEGORICAL, result);
  return val;

This is my exception stack trace  : 

`Parsed Attachment Link:remittanceException in thread "main" java.lang.NumberFormatException: For input string: "remittance"
 at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1250)
 at java.lang.Double.parseDouble(Double.java:540)
 at org.jpmml.evaluator.TypeUtil.parseDouble(TypeUtil.java:208)
 at org.jpmml.evaluator.TypeUtil.parse(TypeUtil.java:89)
 at org.jpmml.evaluator.TypeUtil.parseOrCast(TypeUtil.java:69)
 at org.jpmml.evaluator.FieldValueUtil.create(FieldValueUtil.java:459)
 at org.jpmml.evaluator.FieldValueUtil.refine(FieldValueUtil.java:516)
 at org.jpmml.evaluator.FieldValueUtil.refine(FieldValueUtil.java:485)
 at org.jpmml.evaluator.ExpressionUtil.evaluate(ExpressionUtil.java:59)
 at org.jpmml.evaluator.ModelEvaluationContext.resolve(ModelEvaluationContext.java:133)
 at org.jpmml.evaluator.EvaluationContext.evaluate(EvaluationContext.java:64)
 at org.jpmml.evaluator.ExpressionUtil.evaluateFieldRef(ExpressionUtil.java:232)
 at org.jpmml.evaluator.ExpressionUtil.evaluateExpression(ExpressionUtil.java:82)
 at org.jpmml.evaluator.ExpressionUtil.evaluate(ExpressionUtil.java:66)
 at org.jpmml.evaluator.ExpressionUtil.evaluateApply(ExpressionUtil.java:424)
 at org.jpmml.evaluator.ExpressionUtil.evaluateExpression(ExpressionUtil.java:106)
 at org.jpmml.evaluator.ExpressionUtil.evaluate(ExpressionUtil.java:66)
 at org.jpmml.evaluator.ExpressionUtil.evaluate(ExpressionUtil.java:57)
 at org.jpmml.evaluator.ModelEvaluationContext.resolve(ModelEvaluationContext.java:133)
 at org.jpmml.evaluator.EvaluationContext.evaluate(EvaluationContext.java:64)
 at org.jpmml.evaluator.ExpressionUtil.evaluateFieldRef(ExpressionUtil.java:232)
 at org.jpmml.evaluator.ExpressionUtil.evaluateExpression(ExpressionUtil.java:82)
 at org.jpmml.evaluator.ExpressionUtil.evaluate(ExpressionUtil.java:66)
 at org.jpmml.evaluator.ExpressionUtil.evaluateApply(ExpressionUtil.java:424)
 at org.jpmml.evaluator.ExpressionUtil.evaluateExpression(ExpressionUtil.java:106)
 at org.jpmml.evaluator.ExpressionUtil.evaluate(ExpressionUtil.java:66)
 at org.jpmml.evaluator.ExpressionUtil.evaluate(ExpressionUtil.java:57)
 at org.jpmml.evaluator.ModelEvaluationContext.resolve(ModelEvaluationContext.java:133)
 at org.jpmml.evaluator.EvaluationContext.evaluate(EvaluationContext.java:64)
 at org.jpmml.evaluator.ExpressionUtil.evaluateFieldRef(ExpressionUtil.java:232)
 at org.jpmml.evaluator.ExpressionUtil.evaluateExpression(ExpressionUtil.java:82)
 at org.jpmml.evaluator.ExpressionUtil.evaluate(ExpressionUtil.java:66)
 at org.jpmml.evaluator.ExpressionUtil.evaluate(ExpressionUtil.java:57)
 at org.jpmml.evaluator.ModelEvaluationContext.resolve(ModelEvaluationContext.java:133)
 at org.jpmml.evaluator.EvaluationContext.evaluate(EvaluationContext.java:64)
 at org.jpmml.evaluator.ModelEvaluationContext.resolve(ModelEvaluationContext.java:129)
 at org.jpmml.evaluator.EvaluationContext.evaluate(EvaluationContext.java:64)
 at org.jpmml.evaluator.PredicateUtil.evaluateSimplePredicate(PredicateUtil.java:110)
 at org.jpmml.evaluator.PredicateUtil.evaluatePredicate(PredicateUtil.java:63)
 at org.jpmml.evaluator.PredicateUtil.evaluate(PredicateUtil.java:51)
 at org.jpmml.evaluator.tree.TreeModelEvaluator.evaluateNode(TreeModelEvaluator.java:201)
 at org.jpmml.evaluator.tree.TreeModelEvaluator.handleTrue(TreeModelEvaluator.java:218)
 at org.jpmml.evaluator.tree.TreeModelEvaluator.evaluateTree(TreeModelEvaluator.java:162)
 at org.jpmml.evaluator.tree.TreeModelEvaluator.evaluateClassification(TreeModelEvaluator.java:137)
 at org.jpmml.evaluator.tree.TreeModelEvaluator.evaluate(TreeModelEvaluator.java:106)
 at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluateSegmentation(MiningModelEvaluator.java:407)
 at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluateClassification(MiningModelEvaluator.java:240)
 at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:207)
 at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:185)
 at test.Test2.evaluate(Test2.java:57)
 at test.Test2.main(Test2.java:53)
```

**Comment by vruusmann** [comment]
> `CustomTransformFunctionGenerator(function='ParseText')`

Your `CustomTransformFunction` is creating invalid PMML markup. The JPMML-Evaluator library cannot magically fix invalid markup.

If your transform is passing string values (eg. `"remittance"`) to functions that expect  numeric values, then it's correct for the JPMML-Evaluator library to throw an `java.lang.NumberFormatException`.
