### ISSUE TITLE
Input file for Evaluation Example

### ISSUE THREAD

**Issue by xliu-L1** [jpmml/jpmml-evaluator#79]
Hello,
I am running this line in my cmd window:
C:\Users\admin\Downloads\jpmml-evaluator-master\pmml-evaluator-example>java -cp target/example-1.3-SNAPSHOT.jar org.jpmml.evaluator.EvaluationExample --model model.pmml --input input.csv --output output.csv

I have the model.pmml and input file in input.csv in the C:\Users\admin\Downloads\jpmml-evaluator-master\pmml-evaluator-example\target folder, but I have this error:
Exception in thread "main" java.io.FileNotFoundException: input.csv (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.jpmml.evaluator.Example.readTable(Example.java:108)
        at org.jpmml.evaluator.EvaluationExample.execute(EvaluationExample.java:201)
        at org.jpmml.evaluator.Example.execute(Example.java:86)
        at org.jpmml.evaluator.EvaluationExample.main(EvaluationExample.java:189)

Please advise. Where should my input file be located or is this another issue all together?
(I have also tried absolute paths, but same error)

**Comment by vruusmann** [comment]
> Where should my input file be located?

The model file (`model.pmml`) and the input CSV file (`input.csv`) must be in your working directory. If you execute the Java command in `C:\Users\admin\Downloads\jpmml-evaluator-master\pmml-evaluator-example` directory, then these two files must be inside that directory too.

At the moment you have placed these two files into the `target/` subdirectory.
