### ISSUE TITLE
InvalidResultException

### ISSUE THREAD

**Issue by Alexkevin** [jpmml/jpmml-evaluator#81]
Hi, when I use the evaluator,  I got the following error:
```
Exception in thread "main" org.jpmml.evaluator.InvalidResultException (at or around line 32)
	at org.jpmml.evaluator.FieldValueUtil.performInvalidValueTreatment(FieldValueUtil.java:178)
	at org.jpmml.evaluator.FieldValueUtil.prepareInputValue(FieldValueUtil.java:90)
	at org.jpmml.evaluator.InputField.prepare(InputField.java:64)
	at ResolveModel.predictDetail(ResolveModel.java:43)
	at ResolveModel.main(ResolveModel.java:82)
```

#### I guess when it comes with categorical variable, the error happens. I tested many times

The java code is ：
```java
public class ResolveModel {


    private Evaluator modelEvaluator;
    private LinkedHashMap<String,Double> inputData;

    public ResolveModel(Evaluator modelEvaluator, LinkedHashMap<String,Double> inputData){
        this.modelEvaluator = modelEvaluator;
        this.inputData = inputData;
    }

    public Map<FieldName, ?> predictDetail(){

        Map<FieldName,FieldValue> arguments = new LinkedHashMap<FieldName, FieldValue>();
        List<InputField> inputFields = modelEvaluator.getInputFields();
        for( InputField inputField: inputFields){
            System.out.println(inputField.getName());
            arguments.put(inputField.getName(),inputField.prepare(1.0));

        }

        Map<FieldName,?> results = modelEvaluator.evaluate(arguments);
        Map<FieldName, Object> results_probability  = new LinkedHashMap();
        List<OutputField> outputFields = modelEvaluator.getOutputFields();
        for(OutputField outputField: outputFields){
            FieldName fieldName = outputField.getName();
            results_probability.put(fieldName,results.get(fieldName));
        }

        return results_probability;

    }

    // Test
    public static void main(String[] args) throws Exception{
        PMML pmml;
        InputStream is = new FileInputStream("lightgbm.pmml");
        try {
            pmml = PMMLUtil.unmarshal(is);
        } finally {
            is.close();
        }

        ModelEvaluatorFactory modelEvaluatorFactory = ModelEvaluatorFactory.newInstance();
        ModelEvaluator<?> modelEvaluator = modelEvaluatorFactory.newModelEvaluator(pmml);
        Evaluator evaluator = modelEvaluator;

        LinkedHashMap<String,Double> input1  = new LinkedHashMap<String, Double>();
        List<InputField> inputFields = modelEvaluator.getInputFields();
        for(InputField inputField: inputFields){
            input1.put(inputField.getName().toString(),0.1);
        }

        ResolveModel rm = new ResolveModel(evaluator,input1);
        Map<FieldName,?> results = rm.predictDetail();
        System.out.println(results);


    }

}

```
I also attached my pmml file !  Thank you 
[lightgbm.pmml.zip](https://github.com/jpmml/jpmml-evaluator/files/1469791/lightgbm.pmml.zip)

**Comment by vruusmann** [comment]
Your PMML file contains three continuous and one categorical input field. The valid value range of continuous input fields is defined using the `Interval` element. For example:
```XML
<DataField name="sepal_length_(cm)" optype="continuous" dataType="double">
	<Interval closure="closedClosed" leftMargin="4.3" rightMargin="7.9"/>
</DataField>
```

> for(InputField inputField: inputFields){
>     input1.put(inputField.getName().toString(),0.1);
> }

However, in your Java application code, you're trying to pass `0.1` as the value of the `sepal_length_(cm)` input field. This value is outside of the valid value range `[4.3, 7.9]`, which is why the JPMML-Evaluator library refuses to score this data record by throwing an `InvalidResultException`.

You can disable the generation of `Interval` elements by specifying `ContinuousDomain(with_data = False)` in your Scikit-Learn pipeline. Or you could simply use better input field values - for example, `1.0` and `2.0` should satisfy all validity criteria.
